from sqlalchemy import Boolean, Column, String, TEXT
from sqlalchemy.orm import relationship

from .database import Base


class Data(Base):
    __tablename__ = "alldata_b"

    Publication_Type = Column(TEXT)
    Book_Editors = Column(TEXT)
    Book_Group_Authors = Column(TEXT)
    Author_Full_Names = Column(TEXT)
    Book_Author_Full_Names = Column(TEXT)
    Group_Authors = Column(TEXT)
    Article_Title = Column(TEXT)
    Source_Title = Column(TEXT)
    Book_Series_Title = Column(TEXT)
    Language = Column(TEXT)
    Document_Type = Column(TEXT)
    Conference_Title = Column(TEXT)
    Conference_Date = Column(TEXT)
    Conference_Location = Column(TEXT)
    Conference_Sponsor = Column(TEXT)
    Conference_Host = Column(TEXT)
    Author_Keywords = Column(TEXT)
    Keywords_Plus = Column(TEXT)
    Abstract = Column(TEXT)
    Addresses = Column(TEXT)
    Affiliations = Column(TEXT)
    Reprint_Addresses = Column(TEXT)
    Email_Addresses = Column(TEXT)
    Researcher_Ids = Column(TEXT)
    ORCIDs = Column(TEXT)
    Funding_Orgs = Column(TEXT)
    Funding_Name_Preferred = Column(TEXT)
    Funding_Text = Column(TEXT)
    Cited_Reference_Count = Column(TEXT)
    WoS_Core = Column(TEXT)
    All_Databases = Column(TEXT)
    Day_Usage_Count_180 = Column(TEXT)
    Since_2013_Usage_Count = Column(TEXT)
    Publisher = Column(TEXT)
    Publisher_City = Column(TEXT)
    Publisher_Address = Column(TEXT)
    ISSN = Column(TEXT)
    eISSN = Column(TEXT)
    ISBN = Column(TEXT)
    Journal_Abbreviation = Column(TEXT)
    Journal_ISO_Abbreviation = Column(TEXT)
    Publication_Date = Column(TEXT)
    Publication_Year = Column(TEXT)
    Volume = Column(TEXT)
    Issue = Column(TEXT)
    Part_Number = Column(TEXT)
    Supplement = Column(TEXT)
    Special_Issue = Column(TEXT)
    Meeting_Abstract = Column(TEXT)
    Article_Number = Column(TEXT)
    DOI = Column(TEXT)
    Book_DOI = Column(TEXT)
    Number_of_Pages = Column(TEXT)
    WoS_Categories = Column(TEXT)
    Web_of_Science_Index = Column(TEXT)
    Research_Areas = Column(TEXT)
    IDS_Number = Column(TEXT)
    Pubmed_Id = Column(TEXT)
    Open_Access_Designations = Column(TEXT)
    UT = Column(TEXT, primary_key=True)
